import type { RiskManifestRecord } from "./risk-manifest-types";
import { SERVER_ACTION_RISK_MANIFEST } from "./risk-manifest-server-actions";

export const RISK_MANIFEST_VERSION = 1;

const standardRecovery = {
  killSwitch: "disable affected route in deployment configuration",
  runbook: "docs/operations/risk-register.md",
} as const;

// Pending policies are intentional release blockers. They document a known
// authorization decision that must be assigned before P0 gates are enforced.
const API_RISK_MANIFEST: readonly RiskManifestRecord[] = [
  {
    id: "api-auth",
    kind: "api-route",
    path: "app/api/auth/[...all]/route.ts",
    operation: "ALL",
    tier: "P0",
    dataClassification: "restricted",
    owners: { technical: "security", business: "administration", release: "release" },
    authorization: { reference: "better-auth session and credential policy", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope", "audit", "recovery"],
    recovery: standardRecovery,
  },
  {
    id: "api-avatar-download",
    kind: "api-route",
    path: "app/api/avatars/[...path]/route.ts",
    operation: "GET",
    tier: "P0",
    dataClassification: "confidential",
    owners: { technical: "application", business: "administration", release: "release" },
    authorization: { reference: "owner or administrator avatar access", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope", "audit", "recovery"],
    recovery: standardRecovery,
  },
  {
    id: "api-payment-summary-export",
    kind: "api-route",
    path: "app/api/thanh-toan/tong-hop/export/route.ts",
    operation: "GET",
    tier: "P0",
    dataClassification: "restricted",
    owners: { technical: "application", business: "finance", release: "release" },
    authorization: { reference: "administrator-only until payment records have a verifiable department scope", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope", "audit", "recovery"],
    recovery: standardRecovery,
  },
  {
    id: "api-generic-excel-export",
    kind: "api-route",
    path: "app/api/export/excel/route.ts",
    operation: "POST",
    tier: "P0",
    dataClassification: "restricted",
    owners: { technical: "application", business: "product", release: "release" },
    authorization: { reference: "allowlisted export; project-scoped du-toan, administrator-only where department scope is unavailable", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope", "audit", "recovery"],
    recovery: standardRecovery,
  },
  {
    id: "api-task-attachment",
    kind: "api-route",
    path: "app/api/tasks/[id]/attachments/[attId]/route.ts",
    operation: "DELETE",
    tier: "P0",
    dataClassification: "confidential",
    owners: { technical: "application", business: "operations", release: "release" },
    authorization: { reference: "task viewer download and task editor delete within resource scope", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope", "audit", "recovery"],
    recovery: standardRecovery,
  },
  {
    id: "api-notification-list",
    kind: "api-route",
    path: "app/api/notifications/route.ts",
    operation: "GET",
    tier: "P1",
    dataClassification: "confidential",
    owners: { technical: "application", business: "product", release: "release" },
    authorization: { reference: "current-user notification ownership", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope"],
    recovery: standardRecovery,
  },
  {
    id: "api-notification-stream",
    kind: "api-route",
    path: "app/api/notifications/stream/route.ts",
    operation: "GET",
    tier: "P1",
    dataClassification: "confidential",
    owners: { technical: "application", business: "product", release: "release" },
    authorization: { reference: "current-user notification ownership", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope"],
    recovery: standardRecovery,
  },
  {
    id: "api-cascade-projects",
    kind: "api-route",
    path: "app/api/cong-no/cascade-projects/route.ts",
    operation: "GET",
    tier: "P1",
    dataClassification: "internal",
    owners: { technical: "application", business: "finance", release: "release" },
    authorization: { reference: "cong-no-vat-tu module access", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope"],
    recovery: standardRecovery,
  },
  {
    id: "api-cascade-suppliers",
    kind: "api-route",
    path: "app/api/thanh-toan/cascade-suppliers/route.ts",
    operation: "GET",
    tier: "P1",
    dataClassification: "internal",
    owners: { technical: "application", business: "finance", release: "release" },
    authorization: { reference: "administrator-only until payment records have a verifiable department scope", status: "defined" },
    requiredTests: ["allow", "deny", "cross-scope"],
    recovery: standardRecovery,
  },
  {
    id: "api-health",
    kind: "api-route",
    path: "app/api/health/route.ts",
    operation: "GET",
    tier: "P2",
    dataClassification: "public",
    owners: { technical: "platform", business: "product", release: "release" },
    authorization: { reference: "public health endpoint policy", status: "defined" },
    requiredTests: ["allow", "recovery"],
    recovery: standardRecovery,
  },
];

export const RISK_MANIFEST: readonly RiskManifestRecord[] = [
  ...API_RISK_MANIFEST,
  ...SERVER_ACTION_RISK_MANIFEST,
];
