services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.3.2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e
    container_name: ngoquyen-uptime
    restart: unless-stopped
    ports:
      - "127.0.0.1:8002:3001"
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  uptime-kuma-data:
